### PR TITLE
Add Spanish translation

### PR DESCRIPTION
**Pull request by fitojb**
I gave the .json file indentation merely for ease of reviewing, after which I can collapse it to one line if you so prefer.

### CODE REVIEW

**Comment by yanone** [comment]
Hi Adolfo,
this is absolutely awesome. However, the json file isn't written by hand. It's auto-generated from an online translation interface. I'm planning to invite people to collaborate on it once the interface is finished. It will have convenience features such as notifying you when the original English text has changed etc.
Therefore, I will not merge this PR, but instead take your data and put it into my online database. Will need to program this, because data isn't meant to be uploaded by json file :)
Anyway. Super cool, and we'll stay in touch.

**Comment by fitojb** [comment]
Sounds like a deal =) Thanks!

**Comment by yanone** [comment]
The use of your translations is getting closer!

Bildschirmfoto 2020-01-30 um 13 40 44

I have the new translation web interface online now, but still needs some attention. Will let you know.

**Comment by yanone** [comment]
Hi Adolfo,

it's been a while.
So my online translation interface is finished, and I wanted to get back to your offer to contribute the Spanish translations.

However, meanwhile my colleague at Google Fonts has also offered to care for the Spanish translation, so I've been wondering how eager you really are to do it?

And in case you're okay with her taking over, would you still like to be credited for the translation alongside her? We can credit two people for one language, no problem.

Sorry if it's a bot confusing.
Thank you

**Comment by fitojb** [comment]
@Yanone I’m OK with someone else taking over the translation, and to receive a co-credit; however, I would just like a request: the translation should use the _usted_ treatment as opposed to the _tú_ (informal) treatment that Google likes to use.

**Comment by yanone** [comment]
@fitojb Could you please explain why the formal? I was actually hoping we could stick with informal for all languages wherever possible, and I already translated the German to be informal and wrote it in the description/requirements. But I'm open for your opinion.

**Comment by davelab6** [comment]
To be clear, @vv-monsalve isn't following any google policy or standards
with this, it's just that she and yanone both work on similar projects for
Google Fonts and that's how they know each other.

**Comment by yanone** [comment]
Yeah, the informal is a personal choice of mine. In any case, Type.World is not a Google product, so we operate independent of Google’s conduct.

My personal take is that I think that a software should talk informally to its user – unless cultural specifics of a certain language suggest to really not do that, which is why I asked about your reasoning for it.

**Comment by fitojb** [comment]
In Spanish, _usted_ isn’t necessarily formal (as understood from an English perspective) and _tú_ can be downright rude in places like Colombia.

**Comment by vv-monsalve** [comment]
Here in Colombia, that has changed a lot for some years now, and it depends a lot on the context. For applications in general informal treatment is ok as it is a common standard, but it could also be desirable. Also, the typographic community belongs to a creative environment where informal treatment is welcome. Informal doesn't mean less serious in any case, but friendly.

Lastly, the tone is an important part of brand communication, so it should be determined by it, it's creators and the way the product, in this case the App, wants to address its audience, and for TypeWorld it has been informal.

**Comment by fitojb** [comment]
I would beg to differ. I actually find it weird that software tries to talk to me like a close person. Software in Spanish has historically always been elegantly written — even cell phones using software other than iOS and stock Android treat users respectfully (back when we used Motorola, Sony Ericsson and Nokia phones, all of them consistently used _usted_, similarly, Sailfish and Ubuntu Phone devices used _usted_, and today’s phones from Huawei at least also use _usted_. _Tú_ in software is a very recent phenomenon due, among other reasons besides the influence of English, to the amateurization in the industry of localization, and the excessive reliance on people with no formal training in l10n since the explosion of App Store/Google Play).

In my view, the other reason to back away from _tú_ treatment in translations has to do with the obligatory duplication that has to happen in order to accommodate Cono Sur countries (as well as regions like Chiapas, Mexico) that do not use _tú_ at all, but _vos_. Having to reconjugate all the verbs for _voseo_ in a duplicate localization creates too much strain for small projects and volunteer translations, because both versions have to be maintained in sync. I spoke about this in [LibreOffice’s style guide for Spanish localization](https://wiki.documentfoundation.org/ES/Gu%C3%ADa_de_estilo#Registro). _Tú_ can be adequate for localizing websites and marketing material, but apps tend not to use it, especially those that are cross-platform (because of varying standards across platforms).

**Pull request closed without merging**
